// Code generated by protoc-gen-go-ghttp. DO NOT EDIT.
// versions:
// 	protoc-gen-go-http v0.0.1
// 	protoc             v3.21.8
// source: user/v1/user.proto

package v1

import (
	context "context"
	g "github.com/gogf/gf/v2/frame/g"
)

var _ = context.Background()
var _ = g.Meta{}

// UnimplementedUserServer
type UnimplementedUserServer struct {
	impl UserImpl
}

// RegisterUserServer is an entry that must be implemented.
func RegisterUserServer(impl UserImpl) UnimplementedUserServer {
	return UnimplementedUserServer{impl: impl}
}

// UserImpl is the server API for User service.
type UserImpl interface {
}
