// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: user/v2/user_profile.proto

package v2

import (
	entity "/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户ID
	// v: required
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProfileReq) Reset() {
	*x = ProfileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v2_user_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReq) ProtoMessage() {}

func (x *ProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReq.ProtoReflect.Descriptor instead.
func (*ProfileReq) Descriptor() ([]byte, []int) {
	return file_user_v2_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProfileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *entity.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ProfileRes) Reset() {
	*x = ProfileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v2_user_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRes) ProtoMessage() {}

func (x *ProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRes.ProtoReflect.Descriptor instead.
func (*ProfileRes) Descriptor() ([]byte, []int) {
	return file_user_v2_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileRes) GetUser() *entity.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_v2_user_profile_proto protoreflect.FileDescriptor

var file_user_v2_user_profile_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x32, 0x1a, 0x11, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_v2_user_profile_proto_rawDescOnce sync.Once
	file_user_v2_user_profile_proto_rawDescData = file_user_v2_user_profile_proto_rawDesc
)

func file_user_v2_user_profile_proto_rawDescGZIP() []byte {
	file_user_v2_user_profile_proto_rawDescOnce.Do(func() {
		file_user_v2_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_v2_user_profile_proto_rawDescData)
	})
	return file_user_v2_user_profile_proto_rawDescData
}

var file_user_v2_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v2_user_profile_proto_goTypes = []interface{}{
	(*ProfileReq)(nil),  // 0: user.v2.ProfileReq
	(*ProfileRes)(nil),  // 1: user.v2.ProfileRes
	(*entity.User)(nil), // 2: entity.User
}
var file_user_v2_user_profile_proto_depIdxs = []int32{
	2, // 0: user.v2.ProfileRes.user:type_name -> entity.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v2_user_profile_proto_init() }
func file_user_v2_user_profile_proto_init() {
	if File_user_v2_user_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_v2_user_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v2_user_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_v2_user_profile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v2_user_profile_proto_goTypes,
		DependencyIndexes: file_user_v2_user_profile_proto_depIdxs,
		MessageInfos:      file_user_v2_user_profile_proto_msgTypes,
	}.Build()
	File_user_v2_user_profile_proto = out.File
	file_user_v2_user_profile_proto_rawDesc = nil
	file_user_v2_user_profile_proto_goTypes = nil
	file_user_v2_user_profile_proto_depIdxs = nil
}
