// Code generated by protoc-gen-go-ghttp. DO NOT EDIT.
// versions:
// 	protoc-gen-go-http v0.0.1
// 	protoc             v3.21.8
// source: user/v2/user_profile.proto

package v2

import (
	context "context"
	g "github.com/gogf/gf/v2/frame/g"
)

var _ = context.Background()
var _ = g.Meta{}
